[project]
name = "velov-analytics"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "weart99", email = "arthurparmentier99@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dbt-duckdb>=1.11.0",
    "duckdb>=1.5.5",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "pydeck>=0.9.3",
    "requests>=2.34.2",
    "streamlit>=1.64.0",
    "watchdog>=6.0.0",
]

[project.scripts]
velov-analytics = "velov_analytics:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
